# Generated by Django 3.1 on 2020-08-25 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('points', models.IntegerField(default=0)),
                ('website', models.URLField(blank=True)),
                ('video', models.URLField(blank=True)),
                ('education', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BucketList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wanderlist.activity')),
                ('business_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wanderlist.business')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('rank', models.IntegerField(default=0)),
                ('instagram', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Rewards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed', models.BooleanField()),
                ('reward_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wanderlist.reward')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wanderlist.user')),
            ],
        ),
        migrations.CreateModel(
            name='User_Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wanderlist.activity')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wanderlist.user')),
            ],
        ),
        migrations.CreateModel(
            name='BucketList_Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField()),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wanderlist.activity')),
                ('bucketlist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wanderlist.bucketlist')),
            ],
        ),
        migrations.AddField(
            model_name='bucketlist',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wanderlist.user'),
        ),
        migrations.AddField(
            model_name='activity',
            name='business_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wanderlist.business'),
        ),
    ]
