# Generated by Django 3.0.4 on 2020-09-01 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wanderlist', '0002_reward_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, default='St Lucia QLD', max_length=200),
        ),
    ]
