# Generated by Django 3.0.4 on 2020-09-19 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wanderlist', '0003_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
