# Generated by Django 3.0.4 on 2020-10-19 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wanderlist', '0007_location_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketlist_activity',
            name='fun_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bucketlist_activity',
            name='sustainability_rating',
            field=models.IntegerField(default=0),
        ),
    ]
