# Generated by Django 3.0.4 on 2020-10-23 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wanderlist', '0011_auto_20201023_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imageurl',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
